language: node_js
node_js:
- 'lts/*'
deploy:
  provider: script
  skip_cleanup: true
  script: grunt gh-pages
  on:
    tags: true
    repo: flowhub/bigiot-driver-app
env:
  global:
    secure: asjCE+KpyVtXLMiKStXk2EU43CltRR7YlJhRHnTPxqmvXboE0FLy0aCD7bVmqRbhxwkIGWXC8IFDRuu0SNsi8e1FFlQZY9OkkiGMnIfZ/8W2LFxQNVtHEg2DbThXhpKYIEphuZBTtZXwZyh+t7Hwmuqu5CPRMnGBVp8FzDkCKp0=
