language: node_js
node_js:
- 'lts/*'
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: dist
  keep-history: true
  skip_cleanup: true
  committer-from-gh: true
  on:
    tags: true
